const endpoint = ({
  id,
  group,
  method,
  path,
  title,
  description,
  auth = "public",
  roles = [],
  pathParams = {},
  query = null,
  body = null,
}) => ({
  id,
  group,
  method,
  path,
  title,
  description,
  auth,
  roles,
  pathParams,
  query,
  body,
});

export const apiCatalog = [
  endpoint({
    id: "users-register",
    group: "Users",
    method: "POST",
    path: "/users/register",
    title: "Register user",
    description: "Create a new user account and receive a JWT token.",
    body: {
      full_name: "John Doe",
      email: "john@example.com",
      password: "SecurePassword123!",
      role: "customer",
    },
  }),
  endpoint({
    id: "users-login",
    group: "Users",
    method: "POST",
    path: "/users/login",
    title: "Login user",
    description: "Authenticate and receive a JWT token.",
    body: {
      email: "john@example.com",
      password: "SecurePassword123!",
    },
  }),
  endpoint({
    id: "users-profile-get",
    group: "Users",
    method: "GET",
    path: "/users/profile",
    title: "Get profile",
    description: "Fetch the current authenticated user.",
    auth: "token",
  }),
  endpoint({
    id: "users-profile-update",
    group: "Users",
    method: "PUT",
    path: "/users/profile",
    title: "Update profile",
    description: "Update the current user's profile.",
    auth: "token",
    body: {
      full_name: "John Updated",
      phone_number: "+91-9999999999",
    },
  }),
  endpoint({
    id: "users-list",
    group: "Users",
    method: "GET",
    path: "/users",
    title: "List users",
    description: "Admin-only paginated user list.",
    auth: "token",
    roles: ["admin"],
    query: {
      page: 1,
      limit: 10,
      role: "seller",
      search: "",
    },
  }),

  endpoint({
    id: "addresses-list",
    group: "Addresses",
    method: "GET",
    path: "/addresses",
    title: "List addresses",
    description: "Fetch addresses for the logged-in user.",
    auth: "token",
  }),
  endpoint({
    id: "addresses-create",
    group: "Addresses",
    method: "POST",
    path: "/addresses",
    title: "Create address",
    description: "Create a user shipping or billing address.",
    auth: "token",
    body: {
      full_name: "John Doe",
      phone_number: "+91-9999999999",
      address_type: "shipping",
      address_line1: "221B Baker Street",
      address_line2: "Near City Center",
      city: "Bengaluru",
      state: "Karnataka",
      postal_code: "560001",
      country: "India",
      is_default: true,
    },
  }),
  endpoint({
    id: "addresses-update",
    group: "Addresses",
    method: "PUT",
    path: "/addresses/:id",
    title: "Update address",
    description: "Update a saved address.",
    auth: "token",
    pathParams: { id: "1" },
    body: {
      city: "Mumbai",
      state: "Maharashtra",
      is_default: false,
    },
  }),
  endpoint({
    id: "addresses-delete",
    group: "Addresses",
    method: "DELETE",
    path: "/addresses/:id",
    title: "Delete address",
    description: "Delete an address by id.",
    auth: "token",
    pathParams: { id: "1" },
  }),

  endpoint({
    id: "brands-list",
    group: "Brands",
    method: "GET",
    path: "/brands",
    title: "List brands",
    description: "Fetch all brands.",
  }),
  endpoint({
    id: "brands-get",
    group: "Brands",
    method: "GET",
    path: "/brands/:id",
    title: "Get brand",
    description: "Fetch a brand by id.",
    pathParams: { id: "1" },
  }),
  endpoint({
    id: "brands-create",
    group: "Brands",
    method: "POST",
    path: "/brands",
    title: "Create brand",
    description: "Admin-only brand creation.",
    auth: "token",
    roles: ["admin"],
    body: {
      name: "AudioTech",
      slug: "audiotech",
      description: "Premium audio products",
    },
  }),
  endpoint({
    id: "brands-update",
    group: "Brands",
    method: "PUT",
    path: "/brands/:id",
    title: "Update brand",
    description: "Admin-only brand update.",
    auth: "token",
    roles: ["admin"],
    pathParams: { id: "1" },
    body: {
      name: "AudioTech Pro",
      description: "Updated brand copy",
    },
  }),
  endpoint({
    id: "brands-delete",
    group: "Brands",
    method: "DELETE",
    path: "/brands/:id",
    title: "Delete brand",
    description: "Admin-only brand deletion.",
    auth: "token",
    roles: ["admin"],
    pathParams: { id: "1" },
  }),

  endpoint({
    id: "categories-list",
    group: "Categories",
    method: "GET",
    path: "/categories",
    title: "List categories",
    description: "Fetch all categories.",
  }),
  endpoint({
    id: "categories-get",
    group: "Categories",
    method: "GET",
    path: "/categories/:id",
    title: "Get category",
    description: "Fetch a category by id.",
    pathParams: { id: "1" },
  }),
  endpoint({
    id: "categories-create",
    group: "Categories",
    method: "POST",
    path: "/categories",
    title: "Create category",
    description: "Admin-only category creation.",
    auth: "token",
    roles: ["admin"],
    body: {
      name: "Electronics",
      slug: "electronics",
      description: "Devices and gadgets",
    },
  }),
  endpoint({
    id: "categories-update",
    group: "Categories",
    method: "PUT",
    path: "/categories/:id",
    title: "Update category",
    description: "Admin-only category update.",
    auth: "token",
    roles: ["admin"],
    pathParams: { id: "1" },
    body: {
      name: "Consumer Electronics",
      description: "Updated category description",
    },
  }),
  endpoint({
    id: "categories-delete",
    group: "Categories",
    method: "DELETE",
    path: "/categories/:id",
    title: "Delete category",
    description: "Admin-only category deletion.",
    auth: "token",
    roles: ["admin"],
    pathParams: { id: "1" },
  }),

  endpoint({
    id: "products-list",
    group: "Products",
    method: "GET",
    path: "/products",
    title: "List products",
    description: "Fetch products with filters, search, and pagination.",
    query: {
      page: 1,
      limit: 10,
      search: "",
      category_id: "",
      brand_id: "",
      seller_id: "",
      sort: "created_desc",
    },
  }),
  endpoint({
    id: "products-get",
    group: "Products",
    method: "GET",
    path: "/products/:id",
    title: "Get product",
    description: "Fetch a product by id or slug.",
    pathParams: { id: "wireless-headphones" },
  }),
  endpoint({
    id: "products-create",
    group: "Products",
    method: "POST",
    path: "/products",
    title: "Create product",
    description: "Seller or admin product creation.",
    auth: "token",
    roles: ["admin", "seller"],
    body: {
      name: "Wireless Headphones",
      description: "High quality noise-cancelling headphones.",
      short_description: "Noise-cancelling headphones",
      category_id: 1,
      brand_id: 1,
      base_price: 150,
      selling_price: 120,
      discount_percent: 20,
      initial_stock: 50,
      status: "active",
      sku: "WH-1000",
    },
  }),
  endpoint({
    id: "products-update",
    group: "Products",
    method: "PUT",
    path: "/products/:id",
    title: "Update product",
    description: "Seller or admin product update.",
    auth: "token",
    roles: ["admin", "seller"],
    pathParams: { id: "product-uuid" },
    body: {
      name: "Wireless Headphones Pro",
      selling_price: 129.99,
      status: "active",
    },
  }),
  endpoint({
    id: "products-delete",
    group: "Products",
    method: "DELETE",
    path: "/products/:id",
    title: "Delete product",
    description: "Soft delete a product.",
    auth: "token",
    roles: ["admin", "seller"],
    pathParams: { id: "product-uuid" },
  }),

  endpoint({
    id: "cart-get",
    group: "Cart",
    method: "GET",
    path: "/cart",
    title: "Get cart",
    description: "Fetch the active cart for the logged-in customer.",
    auth: "token",
  }),
  endpoint({
    id: "cart-add-item",
    group: "Cart",
    method: "POST",
    path: "/cart/items",
    title: "Add cart item",
    description: "Add a product or variant to the cart.",
    auth: "token",
    body: {
      product_id: "product-uuid",
      variant_id: null,
      quantity: 2,
    },
  }),
  endpoint({
    id: "cart-update-item",
    group: "Cart",
    method: "PUT",
    path: "/cart/items/:itemId",
    title: "Update cart item",
    description: "Update cart item quantity.",
    auth: "token",
    pathParams: { itemId: "1" },
    body: {
      quantity: 3,
    },
  }),
  endpoint({
    id: "cart-remove-item",
    group: "Cart",
    method: "DELETE",
    path: "/cart/items/:itemId",
    title: "Remove cart item",
    description: "Delete a cart item from the cart.",
    auth: "token",
    pathParams: { itemId: "1" },
  }),
  endpoint({
    id: "cart-clear",
    group: "Cart",
    method: "DELETE",
    path: "/cart/clear",
    title: "Clear cart",
    description: "Remove every item from the active cart.",
    auth: "token",
  }),

  endpoint({
    id: "orders-create",
    group: "Orders",
    method: "POST",
    path: "/orders",
    title: "Create order",
    description: "Checkout the current cart and create seller orders and shipments.",
    auth: "token",
    body: {
      shipping_address_id: 1,
      billing_address_id: 1,
      coupon_id: null,
      notes: "Please leave at front door.",
    },
  }),
  endpoint({
    id: "orders-list",
    group: "Orders",
    method: "GET",
    path: "/orders",
    title: "List orders",
    description: "List the current user's orders, or all for admin depending on token.",
    auth: "token",
    query: {
      page: 1,
      limit: 10,
      status: "",
    },
  }),
  endpoint({
    id: "orders-get",
    group: "Orders",
    method: "GET",
    path: "/orders/:id",
    title: "Get order",
    description: "Fetch one order with seller order and shipment details.",
    auth: "token",
    pathParams: { id: "order-uuid" },
  }),
  endpoint({
    id: "orders-cancel",
    group: "Orders",
    method: "PUT",
    path: "/orders/:id/cancel",
    title: "Cancel order",
    description: "Cancel an order if it is still cancellable.",
    auth: "token",
    pathParams: { id: "order-uuid" },
    body: {
      reason: "Changed my mind",
    },
  }),
  endpoint({
    id: "orders-status",
    group: "Orders",
    method: "PUT",
    path: "/orders/:id/status",
    title: "Update order status",
    description: "Admin-only aggregate order status update.",
    auth: "token",
    roles: ["admin"],
    pathParams: { id: "order-uuid" },
    body: {
      status: "confirmed",
    },
  }),

  endpoint({
    id: "payments-create",
    group: "Payments",
    method: "POST",
    path: "/payments",
    title: "Create payment",
    description: "Create a payment record for an order.",
    auth: "token",
    body: {
      order_id: "order-uuid",
      amount: 283.2,
      payment_method: "upi",
      transaction_id: "txn-123456",
      status: "pending",
    },
  }),
  endpoint({
    id: "payments-by-order",
    group: "Payments",
    method: "GET",
    path: "/payments/order/:orderId",
    title: "Get payments by order",
    description: "Fetch payments attached to an order.",
    auth: "token",
    pathParams: { orderId: "order-uuid" },
  }),
  endpoint({
    id: "payments-status",
    group: "Payments",
    method: "PUT",
    path: "/payments/:id/status",
    title: "Update payment status",
    description: "Admin-only payment status update.",
    auth: "token",
    roles: ["admin"],
    pathParams: { id: "1" },
    body: {
      status: "paid",
    },
  }),

  endpoint({
    id: "shipments-by-order",
    group: "Shipments",
    method: "GET",
    path: "/shipments/order/:orderId",
    title: "Get shipment by order",
    description: "Fetch shipments associated with an order.",
    auth: "token",
    pathParams: { orderId: "order-uuid" },
  }),
  endpoint({
    id: "shipments-update",
    group: "Shipments",
    method: "PUT",
    path: "/shipments/:id",
    title: "Admin update shipment",
    description: "Admin-only shipment update and order sync.",
    auth: "token",
    roles: ["admin"],
    pathParams: { id: "1" },
    body: {
      status: "dispatched",
      tracking_number: "TRACK-001",
      carrier: "BlueDart",
      notes: "Packed and handed over",
    },
  }),

  endpoint({
    id: "seller-orders",
    group: "Seller",
    method: "GET",
    path: "/seller/orders",
    title: "List seller orders",
    description: "Fetch orders assigned to the logged-in seller.",
    auth: "token",
    roles: ["seller"],
    query: {
      page: 1,
      limit: 10,
      status: "",
    },
  }),
  endpoint({
    id: "seller-pack-order",
    group: "Seller",
    method: "PUT",
    path: "/seller/orders/:id/pack",
    title: "Pack seller order",
    description: "Mark a seller order as packed.",
    auth: "token",
    roles: ["seller"],
    pathParams: { id: "1" },
  }),
  endpoint({
    id: "seller-assign-shipper",
    group: "Seller",
    method: "PUT",
    path: "/seller/orders/:id/assign-shipper",
    title: "Assign shipper",
    description: "Assign a shipper to a seller order.",
    auth: "token",
    roles: ["seller"],
    pathParams: { id: "1" },
    body: {
      shipper_id: "shipper-uuid",
      tracking_number: "TRACK-001",
      carrier: "BlueDart",
      estimated_delivery_date: "2026-05-02",
    },
  }),

  endpoint({
    id: "shipper-shipments",
    group: "Shipper",
    method: "GET",
    path: "/shipper/shipments",
    title: "List assigned shipments",
    description: "Fetch shipments assigned to the logged-in shipper.",
    auth: "token",
    roles: ["shipper"],
  }),
  endpoint({
    id: "shipper-shipment-get",
    group: "Shipper",
    method: "GET",
    path: "/shipper/shipments/:id",
    title: "Get assigned shipment",
    description: "Fetch one shipment assigned to the current shipper.",
    auth: "token",
    roles: ["shipper"],
    pathParams: { id: "1" },
  }),
  endpoint({
    id: "shipper-shipment-status",
    group: "Shipper",
    method: "PUT",
    path: "/shipper/shipments/:id/status",
    title: "Update shipment status",
    description: "Update the status of an assigned shipment.",
    auth: "token",
    roles: ["shipper"],
    pathParams: { id: "1" },
    body: {
      status: "in_transit",
      notes: "Shipment picked up by rider",
    },
  }),
  endpoint({
    id: "shipper-shipment-confirm",
    group: "Shipper",
    method: "PUT",
    path: "/shipper/shipments/:id/confirm",
    title: "Confirm delivery",
    description: "Confirm delivery using the shipment OTP.",
    auth: "token",
    roles: ["shipper"],
    pathParams: { id: "1" },
    body: {
      otp: "123456",
    },
  }),

  endpoint({
    id: "reviews-list",
    group: "Reviews",
    method: "GET",
    path: "/reviews/product/:productId",
    title: "List product reviews",
    description: "Fetch reviews for a product.",
    pathParams: { productId: "product-uuid" },
  }),
  endpoint({
    id: "reviews-create",
    group: "Reviews",
    method: "POST",
    path: "/reviews",
    title: "Create review",
    description: "Create a product review.",
    auth: "token",
    body: {
      product_id: "product-uuid",
      order_item_id: 1,
      rating: 5,
      title: "Amazing sound!",
      body: "These headphones are life-changing.",
    },
  }),
  endpoint({
    id: "reviews-delete",
    group: "Reviews",
    method: "DELETE",
    path: "/reviews/:id",
    title: "Delete review",
    description: "Delete a review by id.",
    auth: "token",
    pathParams: { id: "1" },
  }),

  endpoint({
    id: "wishlist-list",
    group: "Wishlist",
    method: "GET",
    path: "/wishlist",
    title: "Get wishlist",
    description: "Fetch the current user's wishlist.",
    auth: "token",
  }),
  endpoint({
    id: "wishlist-add",
    group: "Wishlist",
    method: "POST",
    path: "/wishlist",
    title: "Add wishlist item",
    description: "Add a product or variant to the wishlist.",
    auth: "token",
    body: {
      product_id: "product-uuid",
      variant_id: null,
    },
  }),
  endpoint({
    id: "wishlist-delete",
    group: "Wishlist",
    method: "DELETE",
    path: "/wishlist/:id",
    title: "Remove wishlist item",
    description: "Remove an item from the wishlist.",
    auth: "token",
    pathParams: { id: "1" },
  }),

  endpoint({
    id: "coupons-list",
    group: "Coupons",
    method: "GET",
    path: "/coupons",
    title: "List active coupons",
    description: "Fetch active coupons for the logged-in user.",
    auth: "token",
  }),
  endpoint({
    id: "coupons-validate",
    group: "Coupons",
    method: "POST",
    path: "/coupons/validate",
    title: "Validate coupon",
    description: "Validate a coupon code against a cart total.",
    auth: "token",
    body: {
      code: "SAVE20",
      cart_total: 500,
    },
  }),
  endpoint({
    id: "coupons-create",
    group: "Coupons",
    method: "POST",
    path: "/coupons",
    title: "Create coupon",
    description: "Admin-only coupon creation.",
    auth: "token",
    roles: ["admin"],
    body: {
      code: "SAVE20",
      discount_type: "percent",
      discount_value: 20,
      min_order_amount: 500,
      max_discount_cap: 150,
      valid_from: "2026-04-26T00:00:00.000Z",
      valid_until: "2026-05-31T23:59:59.000Z",
      is_active: true,
    },
  }),
  endpoint({
    id: "coupons-update",
    group: "Coupons",
    method: "PUT",
    path: "/coupons/:id",
    title: "Update coupon",
    description: "Admin-only coupon update.",
    auth: "token",
    roles: ["admin"],
    pathParams: { id: "1" },
    body: {
      discount_value: 25,
      is_active: true,
    },
  }),
  endpoint({
    id: "coupons-delete",
    group: "Coupons",
    method: "DELETE",
    path: "/coupons/:id",
    title: "Delete coupon",
    description: "Admin-only coupon deletion.",
    auth: "token",
    roles: ["admin"],
    pathParams: { id: "1" },
  }),

  endpoint({
    id: "notifications-list",
    group: "Notifications",
    method: "GET",
    path: "/notifications",
    title: "List notifications",
    description: "Fetch current user notifications.",
    auth: "token",
  }),
  endpoint({
    id: "notifications-read",
    group: "Notifications",
    method: "PUT",
    path: "/notifications/:id/read",
    title: "Mark notification read",
    description: "Mark a single notification as read.",
    auth: "token",
    pathParams: { id: "1" },
  }),
  endpoint({
    id: "notifications-read-all",
    group: "Notifications",
    method: "PUT",
    path: "/notifications/read-all",
    title: "Mark all notifications read",
    description: "Mark every current user notification as read.",
    auth: "token",
  }),

  endpoint({
    id: "inventory-by-product",
    group: "Inventory",
    method: "GET",
    path: "/inventory/product/:productId",
    title: "Get inventory by product",
    description: "Seller/admin inventory lookup for a product.",
    auth: "token",
    roles: ["admin", "seller"],
    pathParams: { productId: "product-uuid" },
  }),
  endpoint({
    id: "inventory-update",
    group: "Inventory",
    method: "PUT",
    path: "/inventory/:id",
    title: "Update inventory",
    description: "Seller/admin inventory quantity update.",
    auth: "token",
    roles: ["admin", "seller"],
    pathParams: { id: "1" },
    body: {
      quantity: 42,
      low_stock_threshold: 10,
    },
  }),
  endpoint({
    id: "inventory-low-stock",
    group: "Inventory",
    method: "GET",
    path: "/inventory/low-stock",
    title: "Get low stock items",
    description: "Admin-only low stock inventory report.",
    auth: "token",
    roles: ["admin"],
  }),
];

export const groupOrder = [
  "Users",
  "Addresses",
  "Brands",
  "Categories",
  "Products",
  "Cart",
  "Orders",
  "Payments",
  "Shipments",
  "Seller",
  "Shipper",
  "Reviews",
  "Wishlist",
  "Coupons",
  "Notifications",
  "Inventory",
];
